[package]
name = "vkr-replay"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "vkr-replay"
path = "src/main.rs"

[[bin]]
name = "venus-roundtrip"
path = "src/roundtrip.rs"

[dependencies]
bumpalo = "3.20"
libc = "0.2"
virglrenderer = { package = "virglrs", path = "../../../virglrs" }

[profile.release]
panic = "abort"

[profile.dev]
panic = "abort"
