// SPDX-License-Identifier: MIT
// Copyright © 2026 Gustavo Noronha Silva

//! What a format is, and what GL calls it.
//!
//! Two tables, both generated by `vrend-gen` into `OUT_DIR/vrend/formats.rs` and included here:
//!
//! - [`DESCRIPTIONS`]: gallium's description of every wire format -- block geometry, channels,
//!   swizzle, colour space. This is what `util_format_*` computes in the C, and every size the
//!   transfer path derives (a stride, a layer size, a block count) comes from it. The source is
//!   Mesa's `u_format.yaml`, parsed by Mesa's own parser, so the numbers are the guest's numbers.
//! - [`GL_GROUPS`]: the GL triple (internal format, format, type) vrend gives each format, in the
//!   groups `vrend_formats.c` adds them in and under the condition it adds each group. The host
//!   still has to *probe* them -- whether a triple renders, reads back, or supports texture
//!   storage is the driver's answer, not the table's -- and that lives with the winsys, at
//!   context creation. This module is the static input to that probe.
//!
//! A [`Format`] is a wire number; the description is reached through it and may be absent, since
//! the wire header assigns numbers gallium never named. Every table here that names a format
//! names one with a description, and the tests hold it to that.

use super::features::{Feature, Features};
use super::gl::gles::*;
use super::gl::{GLenum, Gl};
use super::pipe::Swizzle;
use super::proto::{FORMAT_MAX, Format};

#[allow(clippy::all)]
mod generated {
    use super::*;
    include!(concat!(env!("OUT_DIR"), "/vrend/formats.rs"));
}

pub use generated::{DESCRIPTIONS, FORMAT_COUNT, GL_GROUPS};

const _: () =
    assert!(FORMAT_COUNT == FORMAT_MAX as usize, "vrend-gen and proto.rs read different headers");

/// `util_format_layout`.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Layout {
    Plain,
    Subsampled,
    Planar2,
    Planar3,
    S3tc,
    Rgtc,
    Etc,
    Bptc,
    Astc,
    Atc,
    Fxt1,
    Other,
}

/// `util_format_colorspace`.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Colorspace {
    Rgb,
    Srgb,
    Yuv,
    Zs,
}

/// `util_format_type`.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum ChannelType {
    Void,
    Unsigned,
    Signed,
    Fixed,
    Float,
}

/// One channel of a format's block, in memory order.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub struct Channel {
    pub ty: ChannelType,
    pub normalized: bool,
    pub pure: bool,
    pub bits: u32,
}

impl Channel {
    pub const VOID: Channel =
        Channel { ty: ChannelType::Void, normalized: false, pure: false, bits: 0 };
}

/// The unit a format is laid out in: one pixel for plain formats, a 4×4 texel block for
/// s3tc, a byte of eight pixels for R1.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub struct Block {
    pub width: u32,
    pub height: u32,
    pub depth: u32,
    pub bits: u32,
}

/// The format one step across the sRGB/linear divide, by wire number.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Equivalent {
    Srgb(u32),
    Linear(u32),
}

/// `util_format_description`, the parts the renderer reads.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub struct Description {
    pub name: &'static str,
    pub layout: Layout,
    pub block: Block,
    pub nr_channels: u32,
    pub channels: [Channel; 4],
    /// Where each of RGBA (or, in the Zs colour space, depth and stencil) comes from: a channel,
    /// a constant, or nowhere -- `None` is gallium's `PIPE_SWIZZLE_NONE`, the channel that does
    /// not exist, which is how a depth-only format says it has no stencil.
    pub swizzle: [Option<Swizzle>; 4],
    pub colorspace: Colorspace,
    pub is_array: bool,
    pub is_bitmask: bool,
    pub is_mixed: bool,
    pub is_unorm: bool,
    pub is_snorm: bool,
    pub equivalent: Option<Equivalent>,
}

impl Description {
    /// `util_format_get_blocksize`: bytes per block, never zero.
    pub fn block_bytes(&self) -> u32 {
        (self.block.bits / 8).max(1)
    }

    /// `util_format_get_nblocksx`.
    pub fn blocks_wide(&self, width: u32) -> u32 {
        width.div_ceil(self.block.width)
    }

    /// `util_format_get_nblocksy`.
    pub fn blocks_high(&self, height: u32) -> u32 {
        height.div_ceil(self.block.height)
    }

    /// `util_format_get_nblocksz`.
    pub fn blocks_deep(&self, depth: u32) -> u32 {
        depth.div_ceil(self.block.depth)
    }

    /// `util_format_get_stride`: the bytes one row of blocks takes.
    pub fn stride(&self, width: u32) -> u32 {
        self.blocks_wide(width) * self.block_bytes()
    }

    /// `util_format_get_2d_size`: the bytes a `height`-pixel image takes at `stride`.
    pub fn size_2d(&self, stride: u32, height: u32) -> u32 {
        self.blocks_high(height) * stride
    }

    pub fn is_plain(&self) -> bool {
        self.layout == Layout::Plain
    }

    /// `util_format_is_compressed`: block-compressed, the layouts a plain upload cannot describe.
    pub fn is_compressed(&self) -> bool {
        matches!(
            self.layout,
            Layout::S3tc
                | Layout::Rgtc
                | Layout::Etc
                | Layout::Bptc
                | Layout::Astc
                | Layout::Atc
                | Layout::Fxt1
        )
    }

    pub fn is_srgb(&self) -> bool {
        self.colorspace == Colorspace::Srgb
    }

    pub fn has_depth(&self) -> bool {
        self.colorspace == Colorspace::Zs && self.swizzle[0].is_some()
    }

    pub fn has_stencil(&self) -> bool {
        self.colorspace == Colorspace::Zs && self.swizzle[1].is_some()
    }

    pub fn is_depth_or_stencil(&self) -> bool {
        self.has_depth() || self.has_stencil()
    }

    /// `util_format_has_alpha`: a colour format whose alpha is not the constant one.
    pub fn has_alpha(&self) -> bool {
        matches!(self.colorspace, Colorspace::Rgb | Colorspace::Srgb)
            && self.swizzle[3] != Some(Swizzle::One)
    }

    fn first_non_void(&self) -> Option<&Channel> {
        self.channels.iter().find(|c| c.ty != ChannelType::Void)
    }

    /// `util_format_is_pure_integer`: sampled as integers, not normalised -- and stencil-only
    /// counts, since a stencil is an integer.
    pub fn is_pure_integer(&self) -> bool {
        if self.colorspace == Colorspace::Zs {
            return !self.has_depth();
        }
        self.first_non_void().is_some_and(|c| c.pure)
    }

    pub fn is_pure_sint(&self) -> bool {
        self.first_non_void().is_some_and(|c| c.pure && c.ty == ChannelType::Signed)
    }

    pub fn is_pure_uint(&self) -> bool {
        self.first_non_void().is_some_and(|c| c.pure && c.ty == ChannelType::Unsigned)
    }

    /// `util_format_get_component_bits`: the width of RGBA component `component` (or depth and
    /// stencil in the Zs colour space), zero when the format is in another colour space or the
    /// component is a constant. sRGB counts as RGB.
    pub fn component_bits(&self, colorspace: Colorspace, component: usize) -> u32 {
        let linear = |cs| if cs == Colorspace::Srgb { Colorspace::Rgb } else { cs };
        if linear(self.colorspace) != linear(colorspace) {
            return 0;
        }
        match self.swizzle[component] {
            Some(Swizzle::X) => self.channels[0].bits,
            Some(Swizzle::Y) => self.channels[1].bits,
            Some(Swizzle::Z) => self.channels[2].bits,
            Some(Swizzle::W) => self.channels[3].bits,
            _ => 0,
        }
    }
}

impl Format {
    /// The format's description, if the wire number names a format gallium knows.
    pub fn describe(self) -> Option<&'static Description> {
        DESCRIPTIONS[self.wire() as usize].as_ref()
    }

    /// `util_format_name`, without the `PIPE_FORMAT_` prefix.
    pub fn name(self) -> &'static str {
        self.describe().map_or("???", |d| d.name)
    }

    /// The linear format an sRGB format encodes, or itself.
    pub fn linear(self) -> Format {
        match self.describe().and_then(|d| d.equivalent) {
            Some(Equivalent::Linear(n)) => Format::table(n),
            _ => self,
        }
    }

    /// The sRGB format a linear format has, or itself.
    pub fn srgb(self) -> Format {
        match self.describe().and_then(|d| d.equivalent) {
            Some(Equivalent::Srgb(n)) => Format::table(n),
            _ => self,
        }
    }
}

/// The condition `vrend_formats.c` adds a group of GL triples under.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum When {
    Always,
    S3tc,
    Rgtc,
    Bptc,
    /// Added as sampler views only, never probed as a render target: the YUV planar formats.
    SamplerOnly,
    /// The GLES leg's own spellings: BGRA as RGBA with a swizzle, Z32 as Z24.
    Gles,
    Astc,
    Etc2,
    /// The desktop leg's; never added under GLES.
    DesktopGl,
}

/// `vrend_format_table`'s view class: the `glTextureView` compatibility class, which is what
/// decides whether two formats may alias one texture's storage.
#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug)]
pub enum ViewClass {
    Unsupported,
    Bits128,
    Bits96,
    Bits64,
    Bits32,
    Bits16,
    Bits8,
    Rgtc1Red,
    Rgtc2Rg,
    BptcUnorm,
    BptcFloat,
    Dxt1Rgb,
    Dxt1Rgba,
    Dxt3Rgba,
    Dxt5Rgba,
    Etc2Rgb,
    Etc2Rgba,
    Etc2EacRgba,
    Astc4X4,
    Astc5X4,
    Astc5X5,
    Astc6X5,
    Astc6X6,
    Astc8X5,
    Astc8X6,
    Astc8X8,
    Astc10X5,
    Astc10X6,
    Astc10X8,
    Astc10X10,
    Astc12X10,
    Astc12X12,
}

/// One row of `vrend_formats.c`: the GL triple a format is created and uploaded with.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub struct GlFormat {
    pub format: Format,
    pub internalformat: GLenum,
    pub glformat: GLenum,
    pub gltype: GLenum,
    /// A texture swizzle to set on every texture of the format, where GL's channel order is not
    /// the format's.
    pub swizzle: Option<[Swizzle; 4]>,
    pub view_class: ViewClass,
}

/// A group of rows, added together under one condition. Order across groups is the C's: the
/// first group to name a format wins.
#[derive(Clone, Copy, Debug)]
pub struct GlGroup {
    pub name: &'static str,
    pub when: When,
    /// Inserted with sampler-view support and no probe, the way `vrend_add_compressed_formats`
    /// does: the extension that names the group is the whole answer.
    pub compressed: bool,
    pub formats: &'static [GlFormat],
}

/// What the driver said a format can be bound as, from the probe.
#[derive(Clone, Copy, PartialEq, Eq, Debug, Default)]
pub struct Bindings {
    pub sampler_view: bool,
    pub render_target: bool,
    pub depth_stencil: bool,
}

/// A DRM fourcc: the four characters a display controller names a pixel layout by.
///
/// A newtype rather than the `u32`, because the number is only meaningful as those four bytes --
/// `drm_fourcc.h` builds it little-endian from them, and a fourcc compared against a format
/// number or a GL enum is a bug the type prevents rather than a review catches.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub struct DrmFourcc(u32);

impl DrmFourcc {
    /// `fourcc_code`: the four characters, least significant first.
    pub const fn new(code: [u8; 4]) -> DrmFourcc {
        DrmFourcc(u32::from_le_bytes(code))
    }

    pub const fn get(self) -> u32 {
        self.0
    }
}

/// The fourcc a scanout of this format would carry, or `None` for a format no display controller
/// has a name for.
///
/// This is the first half of the C's `vrend_format_can_scanout`, which maps the format to a GBM
/// format and then asks the device about it. The mapping alone is most of the answer: there is no
/// fourcc for a depth/stencil format, a compressed one, or a 64-bit float, so none of them can
/// back a scanout on any device.
pub fn scanout_fourcc(format: Format) -> Option<DrmFourcc> {
    generated::SCANOUT_FOURCCS.iter().find(|(f, _)| *f == format).map(|&(_, code)| code)
}

/// A format's host-side entry: the GL triple, and what the driver answered when asked to make a
/// texture of it -- `vrend_format_table`'s `bindings` and `flags`.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub struct Entry {
    pub gl: GlFormat,
    pub bindings: Bindings,
    /// `glTexStorage2D` accepted the internal format.
    pub can_texture_storage: bool,
    /// `glReadPixels` will hand the format back as the triple says it is: the transfer path's
    /// readback is safe to advertise.
    pub can_readback: bool,
    pub can_multisample: bool,
}

impl Entry {
    /// `VIRGL_TEXTURE_NEED_SWIZZLE`: the triple carries a texture swizzle.
    pub fn need_swizzle(&self) -> bool {
        self.gl.swizzle.is_some()
    }

    /// `vrend_format_can_render`.
    pub fn can_render(&self) -> bool {
        self.bindings.render_target
    }

    /// `vrend_format_is_ds`.
    pub fn is_ds(&self) -> bool {
        self.bindings.depth_stencil
    }
}

/// The host's format table: every wire format the driver accepts, probed once at init the way
/// `vrend_add_formats` probes -- a 32×32 texture per triple, attached to a framebuffer, and the
/// driver's answers recorded. A format not here is one the guest cannot create.
pub struct Table {
    entries: Vec<Option<Entry>>,
}

impl Table {
    /// Probe every group's rows, in the C's order and under the C's conditions, on the context
    /// current on this thread.
    pub fn probe(gl: &Gl, features: &Features) -> Table {
        let mut t = Table { entries: vec![None; FORMAT_COUNT] };
        for group in GL_GROUPS {
            let wanted = match group.when {
                When::Always => true,
                When::S3tc => features.has(Feature::s3tc),
                When::Rgtc => features.has(Feature::rgtc),
                When::Bptc => features.has(Feature::bptc),
                When::Astc => features.has(Feature::astc),
                When::Etc2 => features.has(Feature::etc2),
                When::SamplerOnly | When::Gles => true,
                When::DesktopGl => false,
            };
            if !wanted {
                continue;
            }
            for row in group.formats {
                let at = row.format.wire() as usize;
                if t.entries[at].is_some() {
                    continue;
                }
                if group.compressed || group.when == When::SamplerOnly {
                    t.entries[at] = Some(Entry {
                        gl: *row,
                        bindings: Bindings { sampler_view: true, ..Bindings::default() },
                        can_texture_storage: false,
                        can_readback: false,
                        can_multisample: false,
                    });
                    continue;
                }
                t.entries[at] = probe_row(gl, features, row);
            }
        }
        for e in t.entries.iter_mut().flatten() {
            e.can_texture_storage = texture_storage_works(gl, e.gl.internalformat);
        }
        if features.has(Feature::multisample) && features.has(Feature::storage_multisample) {
            for e in t.entries.iter_mut().flatten() {
                // On GLES a multisample texture is only ever made with `glTexStorage2DMultisample`,
                // so a format without storage has no multisample form.
                e.can_multisample =
                    e.can_texture_storage && multisample_works(gl, e.gl.internalformat);
            }
        }
        t
    }

    /// A table with no driver behind it, for tests of what a table holds.
    #[cfg(test)]
    pub fn empty() -> Table {
        Table { entries: vec![None; FORMAT_COUNT] }
    }

    #[cfg(test)]
    pub fn insert(&mut self, e: Entry) {
        self.entries[e.gl.format.wire() as usize] = Some(e);
    }

    pub fn get(&self, format: Format) -> Option<&Entry> {
        self.entries[format.wire() as usize].as_ref()
    }

    pub fn entries(&self) -> impl Iterator<Item = &Entry> {
        self.entries.iter().flatten()
    }
}

/// `vrend_add_formats`'s probe of one row. `None` when the driver refused the triple.
fn probe_row(gl: &Gl, features: &Features, row: &GlFormat) -> Option<Entry> {
    let tex = gl.gen_texture();
    let fb = gl.gen_framebuffer();
    gl.bind_texture(GL_TEXTURE_2D, Some(tex));
    gl.bind_framebuffer(GL_FRAMEBUFFER, Some(fb));
    gl.drain_errors();
    gl.tex_image_2d_null(GL_TEXTURE_2D, 0, row.internalformat, 32, 32, row.glformat, row.gltype);
    let entry = if gl.drain_errors() != GL_NO_ERROR {
        None
    } else {
        let desc = row.format.describe();
        let is_depth = desc.is_some_and(|d| d.is_depth_or_stencil());
        if is_depth {
            let attachment = if desc.is_some_and(|d| d.has_stencil()) {
                GL_DEPTH_STENCIL_ATTACHMENT
            } else {
                GL_DEPTH_ATTACHMENT
            };
            gl.framebuffer_texture_2d(attachment, GL_TEXTURE_2D, Some(tex), 0);
            gl.draw_buffers(&[GL_NONE]);
        } else {
            gl.framebuffer_texture_2d(GL_COLOR_ATTACHMENT0, GL_TEXTURE_2D, Some(tex), 0);
            gl.draw_buffers(&[GL_COLOR_ATTACHMENT0]);
        }
        let complete = gl.check_framebuffer_status() == GL_FRAMEBUFFER_COMPLETE;
        let bindings = Bindings {
            sampler_view: true,
            render_target: complete && !is_depth,
            depth_stencil: complete && is_depth,
        };
        let can_readback = complete
            && if is_depth {
                depth_stencil_can_readback(features, row.format)
            } else {
                color_can_readback(gl, features, row)
            };
        gl.drain_errors();
        Some(Entry {
            gl: *row,
            bindings,
            can_texture_storage: false,
            can_readback,
            can_multisample: false,
        })
    };
    gl.bind_framebuffer(GL_FRAMEBUFFER, None);
    gl.bind_texture(GL_TEXTURE_2D, None);
    gl.delete_framebuffer(fb);
    gl.delete_texture(tex);
    entry
}

/// `color_format_can_readback`: whether `glReadPixels` on GLES hands this colour format back in
/// its own triple. Asked with the probe framebuffer bound, which is what the implementation
/// read format/type answer for.
fn color_can_readback(gl: &Gl, features: &Features, row: &GlFormat) -> bool {
    match row.format.name() {
        "R8G8B8A8_UNORM" => true,
        "R32G32B32A32_SINT" | "R32G32B32A32_UINT" if features.gles_version >= 30 => true,
        "R32G32B32A32_FLOAT" if features.has(Feature::color_buffer_float) => true,
        "B10G10R10A2_UNORM" | "B10G10R10X2_UNORM" => false,
        _ => {
            gl.get_integer(GL_IMPLEMENTATION_COLOR_READ_TYPE) as GLenum == row.gltype
                && gl.get_integer(GL_IMPLEMENTATION_COLOR_READ_FORMAT) as GLenum == row.glformat
        }
    }
}

/// `depth_stencil_formats_can_readback`: GLES reads depth and stencil back only through the NV
/// extensions.
fn depth_stencil_can_readback(features: &Features, format: Format) -> bool {
    match format.name() {
        "Z16_UNORM" | "Z32_UNORM" | "Z32_FLOAT" | "Z24X8_UNORM" => {
            features.has(Feature::nv_read_depth)
        }
        "Z24_UNORM_S8_UINT" | "S8_UINT_Z24_UNORM" | "Z32_FLOAT_S8X24_UINT" => {
            features.has(Feature::nv_read_depth_stencil)
        }
        "X24S8_UINT" | "S8X24_UINT" | "S8_UINT" => features.has(Feature::nv_read_stencil),
        _ => false,
    }
}

/// `vrend_check_texture_storage`, for one internal format.
fn texture_storage_works(gl: &Gl, internalformat: GLenum) -> bool {
    let tex = gl.gen_texture();
    gl.bind_texture(GL_TEXTURE_2D, Some(tex));
    gl.drain_errors();
    gl.tex_storage_2d(GL_TEXTURE_2D, 1, internalformat, 32, 32);
    let ok = gl.drain_errors() == GL_NO_ERROR;
    gl.bind_texture(GL_TEXTURE_2D, None);
    gl.delete_texture(tex);
    ok
}

/// `vrend_check_texture_multisample`, for one internal format.
fn multisample_works(gl: &Gl, internalformat: GLenum) -> bool {
    let tex = gl.gen_texture();
    gl.bind_texture(GL_TEXTURE_2D_MULTISAMPLE, Some(tex));
    gl.drain_errors();
    gl.tex_storage_2d_multisample(GL_TEXTURE_2D_MULTISAMPLE, 2, internalformat, 32, 32);
    let ok = gl.drain_errors() == GL_NO_ERROR;
    gl.bind_texture(GL_TEXTURE_2D_MULTISAMPLE, None);
    gl.delete_texture(tex);
    ok
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A scanout format is one a display controller has a fourcc for, and nothing else.
    ///
    /// The C reaches this list by mapping to a GBM format and asking the device; the mapping is
    /// the half that holds without a device, and it is what keeps a depth, compressed or
    /// double-precision format -- none of which any display controller can scan out -- from being
    /// advertised as a scanout target. Advertising one is not a cosmetic error: the capset is the
    /// whole of what the guest's driver configures itself from.
    ///
    /// Ground truth: `conversions` in `vrend_winsys_gbm.c`, and `drm_fourcc.h` for the codes.
    #[test]
    fn only_formats_a_display_controller_names_can_be_scanned_out() {
        // The fourcc is those four characters, least significant first -- the layout
        // `drm_fourcc.h` builds. Get the order wrong and every code is silently a different one.
        assert_eq!(DrmFourcc::new(*b"AR24").get(), 0x3432_5241, "fourcc_code('A','R','2','4')");

        // Spot the ones the guest's compositor actually asks for.
        for (name, code) in [("B8G8R8A8_UNORM", *b"AR24"), ("B8G8R8X8_UNORM", *b"XR24")] {
            let format = DESCRIPTIONS
                .iter()
                .position(|d| d.as_ref().is_some_and(|d| d.name == name))
                .map(|i| Format::table(i as u32))
                .unwrap_or_else(|| panic!("{name} is a wire format"));
            assert_eq!(scanout_fourcc(format), Some(DrmFourcc::new(code)), "{name}");
        }

        // Nothing that cannot be a scanout carries one. A fourcc names a packed colour layout, so
        // a depth format, a compressed block and a 64-bit float each have none.
        for (i, d) in DESCRIPTIONS.iter().enumerate() {
            let Some(d) = d else { continue };
            let format = Format::table(i as u32);
            if scanout_fourcc(format).is_none() {
                continue;
            }
            assert_eq!(d.layout, Layout::Plain, "{}: only a plain layout scans out", d.name);
            assert_ne!(
                d.colorspace,
                Colorspace::Zs,
                "{}: a depth/stencil format cannot be scanned out",
                d.name
            );
            assert!(d.block.bits <= 64, "{}: too wide for a scanout", d.name);
        }

        // And the table names every format exactly once.
        let mut seen: Vec<Format> = generated::SCANOUT_FOURCCS.iter().map(|&(f, _)| f).collect();
        let before = seen.len();
        seen.sort_unstable();
        seen.dedup();
        assert_eq!(seen.len(), before, "a format is named twice");
    }

    fn by_name(name: &str) -> (Format, &'static Description) {
        let n = DESCRIPTIONS
            .iter()
            .position(|d| d.is_some_and(|d| d.name == name))
            .unwrap_or_else(|| panic!("no format {name}"));
        let f = Format::from_wire(n as u32).unwrap();
        (f, f.describe().unwrap())
    }

    #[test]
    fn a_plain_format_is_measured_in_bytes_and_a_compressed_one_in_blocks() {
        let (_, bgra) = by_name("B8G8R8A8_UNORM");
        assert_eq!(bgra.block_bytes(), 4);
        assert_eq!(bgra.stride(33), 132);
        assert_eq!(bgra.size_2d(132, 7), 924);
        assert!(bgra.is_plain() && !bgra.is_compressed() && bgra.has_alpha());

        let (_, dxt1) = by_name("DXT1_RGB");
        assert_eq!((dxt1.block.width, dxt1.block.height, dxt1.block_bytes()), (4, 4, 8));
        assert_eq!(dxt1.blocks_wide(33), 9);
        assert_eq!(dxt1.stride(33), 72);
        assert!(dxt1.is_compressed() && !dxt1.has_alpha());

        let (_, r1) = by_name("R1_UNORM");
        assert_eq!((r1.block.width, r1.block_bytes()), (8, 1));
    }

    #[test]
    fn depth_and_stencil_are_read_off_the_swizzle() {
        let (_, z24s8) = by_name("Z24_UNORM_S8_UINT");
        assert!(z24s8.has_depth() && z24s8.has_stencil() && !z24s8.is_pure_integer());
        assert_eq!(z24s8.component_bits(Colorspace::Zs, 0), 24);
        assert_eq!(z24s8.component_bits(Colorspace::Zs, 1), 8);
        assert_eq!(z24s8.component_bits(Colorspace::Rgb, 0), 0);

        let (_, z32) = by_name("Z32_FLOAT");
        assert!(z32.has_depth() && !z32.has_stencil());

        let (_, s8) = by_name("S8_UINT");
        assert!(!s8.has_depth() && s8.has_stencil() && s8.is_pure_integer());
        assert!(!s8.has_alpha());
    }

    #[test]
    fn integer_formats_are_told_from_normalised_ones_by_the_first_channel() {
        let (_, sint) = by_name("R32G32B32A32_SINT");
        assert!(sint.is_pure_integer() && sint.is_pure_sint() && !sint.is_pure_uint());
        let (_, uint) = by_name("R8_UINT");
        assert!(uint.is_pure_uint() && !uint.is_pure_sint());
        let (_, unorm) = by_name("R8G8B8A8_UNORM");
        assert!(!unorm.is_pure_integer() && unorm.is_unorm);
        assert_eq!(unorm.component_bits(Colorspace::Srgb, 3), 8);
        let (_, rgbx) = by_name("R8G8B8X8_UNORM");
        assert_eq!(rgbx.component_bits(Colorspace::Rgb, 3), 0);
        assert!(!rgbx.has_alpha());
    }

    #[test]
    fn srgb_and_linear_point_at_each_other() {
        let (rgba, _) = by_name("R8G8B8A8_UNORM");
        let (srgb, _) = by_name("R8G8B8A8_SRGB");
        assert_eq!(rgba.srgb(), srgb);
        assert_eq!(srgb.linear(), rgba);
        assert_eq!(rgba.linear(), rgba);
        assert_eq!(srgb.srgb(), srgb);
        assert!(srgb.describe().unwrap().is_srgb());
        for (n, d) in DESCRIPTIONS.iter().enumerate() {
            let Some(d) = d else { continue };
            let f = Format::from_wire(n as u32).unwrap();
            match d.equivalent {
                Some(Equivalent::Srgb(_)) => assert_eq!(f.srgb().linear(), f, "{}", d.name),
                Some(Equivalent::Linear(_)) => assert_eq!(f.linear().srgb(), f, "{}", d.name),
                None => {}
            }
        }
    }

    #[test]
    fn every_gl_row_names_a_described_format_once() {
        let mut seen = std::collections::HashSet::new();
        for group in GL_GROUPS {
            assert!(!group.formats.is_empty(), "{} is empty", group.name);
            for row in group.formats {
                let desc = row
                    .format
                    .describe()
                    .unwrap_or_else(|| panic!("{}: {:?}", group.name, row.format));
                assert!(
                    seen.insert((group.name, row.format)),
                    "{} repeats {}",
                    group.name,
                    desc.name
                );
                assert!(
                    row.internalformat != 0 && row.gltype != 0 && row.glformat != 0,
                    "{}",
                    desc.name
                );
            }
        }
        assert_eq!(GL_GROUPS.len(), 31);
        assert!(GL_GROUPS.iter().any(|g| g.when == When::Gles && g.name == "gles_bgra_formats"));
        assert!(GL_GROUPS.iter().filter(|g| g.compressed).count() == 6);
    }

    #[test]
    fn the_wire_names_the_formats_the_c_reaches_through_aliases() {
        // gallium spells these through an alias the wire header does not have; the generator has
        // to resolve them or the YUV group silently loses its rows.
        let (nv12, d) = by_name("Y8_U8V8_420_UNORM");
        assert_eq!(d.layout, Layout::Planar2);
        let (_, rgrb) = by_name("R8G8_R8B8_422_UNORM");
        assert_eq!(rgrb.layout, Layout::Subsampled);
        let yuv = GL_GROUPS.iter().find(|g| g.name == "yuv_planar_formats").unwrap();
        assert!(yuv.formats.iter().any(|r| r.format == nv12));
        assert_eq!(yuv.when, When::SamplerOnly);
    }

    #[test]
    fn a_number_the_wire_never_named_has_no_description() {
        assert!(Format::from_wire(73).unwrap().describe().is_none());
        assert_eq!(Format::from_wire(73).unwrap().name(), "???");
        assert_eq!(Format::NONE.name(), "NONE");
    }
}
