#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright © 2026 Gustavo Noronha Silva
#
# Emit vrend-replay-formats.h: virgl format number -> bytes per block, and the block's width and
# height in texels.
#
# The replay used to assume four bytes per texel everywhere, and said so in a comment: "which is
# what every format this scores actually is". That held until a corpus contained an
# R32G32B32A32_FLOAT render target, at which point the zeroing transfer offered a stride four
# times too small, vrend refused it, the refusal latched the context's in_error, and every later
# submit in the corpus was dropped -- 404 of them -- which reads as a renderer that stopped
# drawing rather than as a harness that guessed.
#
# So the size is taken from the same two files the renderer takes it from and nowhere else:
# src/virgl_hw.h for the wire numbers and src/gallium/auxiliary/util/u_format.yaml for the block
# geometry. Regenerate with:
#
#   ./gen-format-table.py > vrend-replay-formats.h
import re, sys, yaml, pathlib

root = pathlib.Path(__file__).resolve().parents[2]

body = re.search(r"enum virgl_formats\s*\{(.*?)\};", (root / "src/virgl_hw.h").read_text(), re.S).group(1)
num, by_num = -1, {}
for line in body.splitlines():
    line = line.split("/*")[0].strip().rstrip(",")
    if not line.startswith("VIRGL_FORMAT_"):
        continue
    if "=" in line:
        name, value = (x.strip() for x in line.split("="))
        num = int(value, 0)
    else:
        name = line
        num += 1
    by_num[num] = name[len("VIRGL_FORMAT_"):]

geom = {}
for f in yaml.safe_load((root / "src/gallium/auxiliary/util/u_format.yaml").read_text()):
    bits = 0
    for ch in f.get("channels", []):
        m = re.search(r"(\d+)$", str(ch))
        bits += int(m.group(1)) if m else 0
    b = f["block"]
    geom[f["name"]] = (bits // 8, b["width"], b["height"])

hi = max(by_num)
out = ["/* Generated by gen-format-table.py -- do not edit. */", "",
       "#define VREND_REPLAY_MAX_FORMAT %d" % hi, "",
       "struct vrend_replay_format { uint8_t block_bytes, block_w, block_h; };", "",
       "static const struct vrend_replay_format vrend_replay_formats[VREND_REPLAY_MAX_FORMAT + 1] = {"]
known = 0
for n in range(hi + 1):
    name = by_num.get(n)
    g = geom.get(name) if name else None
    if not g or g[0] == 0:
        continue
    known += 1
    out.append("   [%d] = { %d, %d, %d },   /* %s */" % (n, g[0], g[1], g[2], name))
out += ["};", ""]
print("\n".join(out))
print("/* %d of %d format numbers carry a block size; the rest are unknown to this tree and a"
      "\n   caller must treat them as such rather than assuming one. */" % (known, hi + 1),
      file=sys.stderr)
