#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright © 2026 the limina authors
"""Generate the Rust venus protocol from venus-protocol's model.

    gen.py --outdir <dir> [--protocol <venus-protocol checkout>]

The model (`vkxml.py`) and the type selection (`vn_protocol.py`'s `Gen`) are imported from the
venus-protocol subproject over `sys.path`. Nothing is edited there: it is wrap-managed, and the
next re-clone would eat any change. The Rust backend is `rustgen.py` and `templates/`.
"""

import argparse
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

HERE = Path(__file__).parent.resolve()
DEFAULT_PROTOCOL = HERE.parent.parent / 'subprojects' / 'venus-protocol-1.0'


def api_constants(vk_xml):
    """vk.xml's "API Constants", which are the static array dimensions.

    The C generator does not need them -- it includes vulkan.h -- so the model does not carry them.
    They are parsed from the same pinned vk.xml the rest of the model comes from, rather than
    transcribed, so they cannot drift out of step with it.
    """
    consts = {}
    for enums in ET.parse(vk_xml).getroot().iter('enums'):
        if enums.get('name') != 'API Constants':
            continue
        for e in enums.iter('enum'):
            val = e.get('value')
            if val is None or not val.strip().isdigit():
                continue
            consts[e.get('name')] = int(val)
    assert consts, 'no API Constants in %s' % vk_xml
    return consts


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--outdir', required=True, help='Where to write the .rs files.')
    parser.add_argument('--protocol', default=str(DEFAULT_PROTOCOL),
                        help='The venus-protocol checkout to take the model from.')
    args = parser.parse_args()

    protocol = Path(args.protocol).resolve()
    sys.path.insert(0, str(protocol))
    sys.path.insert(0, str(HERE))

    import vn_protocol
    from vkxml import VkRegistry, VkType
    from mako.lookup import TemplateLookup
    from mako.template import Template

    from rustgen import RustGen

    reg = VkRegistry.parse(vn_protocol.VN_PROTOCOL_VK_XML, vn_protocol.VN_PROTOCOL_PRIVATE_XMLS)
    gen = vn_protocol.Gen(False, reg)
    rust = RustGen(gen, api_constants(protocol / 'xmls' / 'vk.xml'))

    lookup = TemplateLookup(str(HERE / 'templates'))
    outdir = Path(args.outdir)
    outdir.mkdir(parents=True, exist_ok=True)

    banner = ('// Generated by virglrs/venus-gen from venus-protocol. Do not edit: the next build\n'
              '// overwrites it, and a fix made here is a fix no one will find. Edit the templates.\n\n')

    for name in ['types.rs']:
        template = Template(filename=str(HERE / 'templates' / name), lookup=lookup,
                            output_encoding='utf-8')
        body = template.render(GEN=gen, RUST=rust, VkType=VkType)
        (outdir / name).write_bytes(banner.encode() + body)

    gaps = []
    header = (Path(HERE / 'templates' / 'serialize.rs.head').read_text())
    (outdir / 'serialize.rs').write_bytes(
        banner.encode() + header.encode() + rust.render_serialize(gaps).encode())

    # Shapes the emitter has not been taught, named where a reader will find them. A gap emits a
    # stub that poisons the stream, so the wire round trip fails on the first command needing one.
    (outdir / 'gaps.txt').write_text('\n'.join(sorted(set(gaps))) + '\n')
    if gaps:
        print('venus-gen: %d members in %d shapes not yet emitted (see gaps.txt)'
              % (len(gaps), len(set(gaps))), file=sys.stderr)


if __name__ == '__main__':
    main()
