#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright © 2026 the limina authors
"""Generate the Rust venus protocol from venus-protocol's model.

    gen.py --outdir <dir> [--protocol <venus-protocol checkout>]

The model (`vkxml.py`) and the type selection (`vn_protocol.py`'s `Gen`) are imported from the
venus-protocol subproject over `sys.path`. Nothing is edited there: it is wrap-managed, and the
next re-clone would eat any change. The Rust backend is `rustgen.py` and `templates/`.
"""

import argparse
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

HERE = Path(__file__).parent.resolve()
DEFAULT_PROTOCOL = HERE.parent.parent / 'subprojects' / 'venus-protocol-1.0'


def api_constants(vk_xml):
    """vk.xml's "API Constants", which are the static array dimensions.

    The C generator does not need them -- it includes vulkan.h -- so the model does not carry them.
    They are parsed from the same pinned vk.xml the rest of the model comes from, rather than
    transcribed, so they cannot drift out of step with it.
    """
    consts = {}
    for enums in ET.parse(vk_xml).getroot().iter('enums'):
        if enums.get('name') != 'API Constants':
            continue
        for e in enums.iter('enum'):
            val = e.get('value')
            if val is None or not val.strip().isdigit():
                continue
            consts[e.get('name')] = int(val)
    assert consts, 'no API Constants in %s' % vk_xml
    return consts


def member_order(xmls):
    """Each struct's members in the order the registry declares them, by name.

    The model does not keep this: `vkxml.py`'s `_sort_struct_members` moves a length member ahead
    of the array it measures, so that the decoder meets the count before it needs it. That is the
    order the *wire* wants, and it is what both generators serialize in.

    It is not the order the struct is laid out in. C takes its layout from vulkan.h, where the
    members stand as declared, and a driver handed one of ours reads it at those offsets. Emitting
    the wire's order as the struct's would swap `VkHostAddressRangeEXT`'s address and size for
    every driver that ever sees one.
    """
    order = {}
    for xml in xmls:
        for ty in ET.parse(xml).getroot().iter('type'):
            if ty.get('category') not in ('struct', 'union') or ty.get('alias'):
                continue
            names = [m.find('name').text for m in ty.iter('member') if m.find('name') is not None]
            if names:
                order[ty.get('name')] = names
    return order


def bitfield_types(vk_xml):
    """The structs vk.xml declares with C bit-fields, by name.

    The model drops the widths -- `vkxml.py` reads the member name and not the `:24` after it --
    so both generators serialize these as whole members, and the two agree on the wire. What they
    cannot agree on is memory: our struct spends a word per member where C packs four into two.

    That divergence is allowed to stand, and vk.xml says why in a comment of its own: the
    bitfields "are non-normative since bitfield ordering is implementation-defined in C". Every
    one of these is acceleration-structure payload the application writes into device memory, so
    none is ever a Vulkan command's parameter and no driver reads our copy. They are excluded from
    the layout oracle because there is no contract there to hold them to.
    """
    types = {}
    for ty in ET.parse(vk_xml).getroot().iter('type'):
        if ty.get('category') != 'struct':
            continue
        members = {m.find('name').text for m in ty.iter('member')
                   if (m.find('name').tail or '').strip().startswith(':')}
        if members:
            types[ty.get('name')] = members
    return types


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--outdir', required=True, help='Where to write the .rs files.')
    parser.add_argument('--protocol', default=str(DEFAULT_PROTOCOL),
                        help='The venus-protocol checkout to take the model from.')
    args = parser.parse_args()

    protocol = Path(args.protocol).resolve()
    sys.path.insert(0, str(protocol))
    sys.path.insert(0, str(HERE))

    import vn_protocol
    from vkxml import VkRegistry, VkType
    from mako.lookup import TemplateLookup
    from mako.template import Template

    from rustgen import RustGen

    reg = VkRegistry.parse(vn_protocol.VN_PROTOCOL_VK_XML, vn_protocol.VN_PROTOCOL_PRIVATE_XMLS)
    gen = vn_protocol.Gen(False, reg)
    vk_xml = protocol / 'xmls' / 'vk.xml'
    rust = RustGen(gen, api_constants(vk_xml), bitfield_types(vk_xml),
                   member_order([vn_protocol.VN_PROTOCOL_VK_XML]
                                + list(vn_protocol.VN_PROTOCOL_PRIVATE_XMLS)))

    lookup = TemplateLookup(str(HERE / 'templates'))
    outdir = Path(args.outdir)
    outdir.mkdir(parents=True, exist_ok=True)

    banner = ('// Generated by virglrs/venus-gen from venus-protocol. Do not edit: the next build\n'
              '// overwrites it, and a fix made here is a fix no one will find. Edit the templates.\n\n')

    for name in ['types.rs']:
        template = Template(filename=str(HERE / 'templates' / name), lookup=lookup,
                            output_encoding='utf-8')
        body = template.render(GEN=gen, RUST=rust, VkType=VkType)
        (outdir / name).write_bytes(banner.encode() + body)

    (outdir / 'info.rs').write_bytes(
        banner.encode() + rust.render_info(vn_protocol).encode())

    c_banner = ('/* Generated by virglrs/venus-gen from venus-protocol. Do not edit: the next build\n'
                ' * overwrites it, and a fix made here is a fix no one will find. Edit the templates. */\n\n')
    (outdir / 'reply_oracle.c').write_bytes(
        c_banner.encode() + rust.render_reply_oracle().encode())
    (outdir / 'layout_oracle.c').write_bytes(
        c_banner.encode() + rust.render_layout_oracle().encode())

    layout_head = (Path(HERE / 'templates' / 'layout.rs.head').read_text())
    (outdir / 'layout.rs').write_bytes(
        banner.encode() + layout_head.encode() + rust.render_layout_table().encode())

    proc_head = (Path(HERE / 'templates' / 'proc.rs.head').read_text())
    (outdir / 'proc.rs').write_bytes(
        banner.encode() + proc_head.encode() + rust.render_proc_table().encode())

    gaps = []
    header = (Path(HERE / 'templates' / 'serialize.rs.head').read_text())
    (outdir / 'serialize.rs').write_bytes(
        banner.encode() + header.encode() + rust.render_serialize(gaps).encode())

    fill_head = (Path(HERE / 'templates' / 'fill.rs.head').read_text())
    (outdir / 'fill.rs').write_bytes(
        banner.encode() + fill_head.encode() + rust.render_fill(gaps).encode())

    # Shapes the emitter has not been taught, named where a reader will find them. A gap emits a
    # stub that poisons the stream, so the wire round trip fails on the first command needing one.
    (outdir / 'gaps.txt').write_text('\n'.join(sorted(set(gaps))) + '\n')
    if gaps:
        print('venus-gen: %d members in %d shapes not yet emitted (see gaps.txt)'
              % (len(gaps), len(set(gaps))), file=sys.stderr)


if __name__ == '__main__':
    main()
