// SPDX-License-Identifier: MIT
// Copyright © 2026 Gustavo Noronha Silva

//! The C ABI's types, transcribed from `src/virglrenderer.h`.
//!
//! Layouts here are checked against `harness/abi/layout.txt`, which is generated by the compiler
//! from the header itself -- a field offset that drifts compiles clean on both sides and corrupts
//! at run time, so it is pinned rather than reviewed.

use std::ffi::{c_char, c_int, c_void};

pub const CALLBACKS_VERSION: c_int = 4;

// virgl_renderer_init flags.
pub const USE_EGL: c_int = 1;
pub const THREAD_SYNC: c_int = 2;
pub const USE_GLX: c_int = 1 << 2;
pub const USE_SURFACELESS: c_int = 1 << 3;
pub const USE_GLES: c_int = 1 << 4;
pub const VENUS: c_int = 1 << 6;
pub const NO_VIRGL: c_int = 1 << 7;
pub const ASYNC_FENCE_CB: c_int = 1 << 8;
pub const RENDER_SERVER: c_int = 1 << 9;
pub const DRM: c_int = 1 << 10;
pub const USE_VIDEO: c_int = 1 << 11;
/// The VMM cannot inject pages, so blobs come from the guest's own heap.
pub const USE_GUEST_VRAM: c_int = 1 << 14;

/// A context's capset is the low byte of the flags it was created with.
pub const CAPSET_MASK: u32 = 0xff;
/// `VIRTGPU_DRM_CAPSET_VIRGL2`, the capset the flagless `virgl_renderer_context_create` binds.
pub const CAPSET_VIRGL2: u32 = 2;

/// `blob_mem` and `fd_type` values, from `virglrenderer.h`. Only the ones the import path accepts
/// are named; the rest are refused by not being here.
pub const BLOB_MEM_HOST3D: u32 = 0x0002;
pub const BLOB_MEM_GUEST_VRAM: u32 = 0x0004;
pub const BLOB_FD_TYPE_DMABUF: u32 = 0x0001;
pub const BLOB_FD_TYPE_OPAQUE: u32 = 0x0002;
pub const BLOB_FD_TYPE_SHM: u32 = 0x0003;

/// `map_info` cache modes, from `virglrenderer.h`. `VIRGL_RENDERER_MAP_CACHE_NONE` is deliberately
/// absent: it is the C's way of saying "there is nothing to map", which here is a refusal with a
/// reason rather than a value the caller has to recognize.
pub const MAP_CACHE_CACHED: u32 = 0x01;
pub const MAP_CACHE_WC: u32 = 0x03;

/// `virgl_renderer_gl_ctx_param`: what the renderer asks the VMM to mint a GL context with.
///
/// Field order is the header's, which is not the order the fields are used in: `shared` sits
/// between the struct's version and the API version it asks for.
#[repr(C)]
pub struct GlCtxParam {
    /// The struct's own version, not the client API's. The C passes 2 and nothing reads it.
    pub version: c_int,
    pub shared: bool,
    pub major_ver: c_int,
    pub minor_ver: c_int,
    /// An `int` in the header, beside a `bool`; kept as it is written there.
    pub compat_ctx: c_int,
}

#[repr(C)]
pub struct Callbacks {
    pub version: c_int,
    pub write_fence: Option<extern "C" fn(*mut c_void, u32)>,
    pub create_gl_context:
        Option<extern "C" fn(*mut c_void, c_int, *mut GlCtxParam) -> *mut c_void>,
    pub destroy_gl_context: Option<extern "C" fn(*mut c_void, *mut c_void)>,
    pub make_current: Option<extern "C" fn(*mut c_void, c_int, *mut c_void) -> c_int>,
    pub get_drm_fd: Option<extern "C" fn(*mut c_void) -> c_int>,
    pub write_context_fence: Option<extern "C" fn(*mut c_void, u32, u32, u64)>,
    pub get_server_fd: Option<extern "C" fn(*mut c_void, u32) -> c_int>,
    pub get_egl_display: Option<extern "C" fn(*mut c_void) -> *mut c_void>,
}

#[repr(C)]
pub struct ResourceCreateArgs {
    pub handle: u32,
    pub target: u32,
    pub format: u32,
    pub bind: u32,
    pub width: u32,
    pub height: u32,
    pub depth: u32,
    pub array_size: u32,
    pub last_level: u32,
    pub nr_samples: u32,
    pub flags: u32,
}

#[repr(C)]
pub struct ResourceInfo {
    pub handle: u32,
    pub virgl_format: u32,
    pub width: u32,
    pub height: u32,
    pub depth: u32,
    pub flags: u32,
    pub tex_id: u32,
    pub stride: u32,
    pub drm_fourcc: c_int,
    pub fd: c_int,
}

#[repr(C)]
pub struct ResourceInfoExt {
    pub version: c_int,
    pub base: ResourceInfo,
    pub has_dmabuf_export: bool,
    pub planes: c_int,
    pub modifiers: u64,
    pub d3d_tex2d: *mut c_void,
}

#[repr(C)]
pub struct CreateBlobArgs {
    pub res_handle: u32,
    pub ctx_id: u32,
    pub blob_mem: u32,
    pub blob_flags: u32,
    pub blob_id: u64,
    pub size: u64,
    pub iovecs: *const libc::iovec,
    pub num_iovs: u32,
}

#[repr(C)]
pub struct ImportBlobArgs {
    pub res_handle: u32,
    pub blob_mem: u32,
    pub fd_type: u32,
    pub fd: c_int,
    pub size: u64,
}

#[repr(C)]
pub struct Box3 {
    pub x: u32,
    pub y: u32,
    pub z: u32,
    pub w: u32,
    pub h: u32,
    pub d: u32,
}

pub type DebugCallback = Option<extern "C" fn(*const c_char, *mut c_void)>;
pub type LogCallback = Option<extern "C" fn(c_int, *const c_char, *mut c_void)>;
pub type FreeDataCallback = Option<extern "C" fn(*mut c_void)>;

/// `virgl_renderer_execute`'s structure tags, from `virglrenderer.h`. They are a bitmask as well
/// as an enum: `SupportedStructures` answers with the union of the ones this build serves.
pub const STRUCTURE_TYPE_EXPORT_QUERY: u32 = 1 << 0;
pub const STRUCTURE_TYPE_SUPPORTED_STRUCTURES: u32 = 1 << 1;

/// `DRM_FORMAT_MOD_INVALID`, from `drm_fourcc.h` by way of `vrend_winsys.h`. "No modifier is
/// being stated", which is the only honest thing to say about storage that has no dma-buf.
pub const DRM_FORMAT_MOD_INVALID: u64 = 0x00ff_ffff_ffff_ffff;

/// The header every `virgl_renderer_execute` request begins with.
///
/// `size` is the caller's own statement of how long its struct is, and it is checked against the
/// struct the tag names rather than trusted: the two are a pair the caller could get wrong, and
/// this is the boundary that reconciles them (CLAUDE.md).
#[repr(C)]
pub struct ExecuteHdr {
    pub stype: u32,
    pub stype_version: u32,
    pub size: u32,
}

/// `struct virgl_renderer_export_query`.
#[repr(C)]
pub struct ExportQuery {
    pub hdr: ExecuteHdr,
    pub in_resource_id: u32,
    pub out_num_fds: u32,
    pub in_export_fds: u32,
    pub out_fourcc: u32,
    pub pad: u32,
    pub out_fds: [c_int; 4],
    pub out_strides: [u32; 4],
    pub out_offsets: [u32; 4],
    pub out_modifier: u64,
}

/// `struct virgl_renderer_supported_structures`.
#[repr(C)]
pub struct SupportedStructures {
    pub hdr: ExecuteHdr,
    pub in_stype_version: u32,
    pub out_supported_structures_mask: u32,
}

/// A pointer the VMM owns and we only ever hand back to it.
///
/// The renderer is reached from more than one thread through the ABI, so its state must be `Send`
/// and -- once ring threads read the resource table alongside the caller -- `Sync`; a bare
/// `*mut c_void` is neither. Wrapping it here, in the module that IS the FFI boundary, keeps the
/// `unsafe impl` where such a thing belongs instead of spreading it through the renderer.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
#[repr(transparent)]
pub struct VmmPtr(pub *mut c_void);

// SAFETY: opaque to us. Nothing in this crate dereferences a VmmPtr -- `priv_` is handed straight
// back through `resource_get_priv`, and a guest iovec's base is read only by code that has the
// VMM's guarantee the mapping is live. Moving the VALUE between threads dereferences nothing.
unsafe impl Send for VmmPtr {}

// SAFETY: the same invariant, and for the same reason. A shared reference to a VmmPtr grants only
// the ability to copy the value out, which is exactly what `Send` already permits; there is no
// interior mutability and no deref for two threads to race on. If anything here ever does
// dereference one, both of these impls are wrong together.
unsafe impl Sync for VmmPtr {}

impl VmmPtr {
    pub const NULL: VmmPtr = VmmPtr(std::ptr::null_mut());
}

/// One entry of a guest-memory scatter list, as the VMM described it.
///
/// A copy of the description, never of the pages: the VMM owns the mapping and may detach it.
#[derive(Clone, Copy, Debug)]
pub struct GuestIov {
    pub base: VmmPtr,
    pub len: usize,
}

impl GuestIov {
    /// # Safety
    /// `iov` must point to `n` valid `iovec` entries for the duration of the call.
    pub unsafe fn from_raw(iov: *const libc::iovec, n: u32) -> Vec<GuestIov> {
        if iov.is_null() || n == 0 {
            return Vec::new();
        }
        // SAFETY: the caller guarantees `n` valid entries at `iov`; the descriptions are copied
        // out and the array itself is never retained.
        let s = unsafe { std::slice::from_raw_parts(iov, n as usize) };
        s.iter().map(|e| GuestIov { base: VmmPtr(e.iov_base), len: e.iov_len }).collect()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// `virgl_renderer_init` reads `Callbacks` field by field rather than through a `&Callbacks`,
    /// because the C's struct is size-versioned and so is shorter than ours for anything below v4.
    /// Those projections are in bounds only if our field order matches the header's, so pin the
    /// offsets.
    ///
    /// Ground truth: `offsetof` under `cc` on `src/virglrenderer.h`.
    #[test]
    fn callbacks_offsets_match_the_c_header() {
        use std::mem::{offset_of, size_of};
        assert_eq!(offset_of!(Callbacks, version), 0);
        assert_eq!(offset_of!(Callbacks, write_fence), 8);
        assert_eq!(offset_of!(Callbacks, create_gl_context), 16);
        assert_eq!(offset_of!(Callbacks, destroy_gl_context), 24);
        assert_eq!(offset_of!(Callbacks, make_current), 32);
        assert_eq!(offset_of!(Callbacks, get_drm_fd), 40);
        assert_eq!(offset_of!(Callbacks, write_context_fence), 48);
        assert_eq!(offset_of!(Callbacks, get_server_fd), 56);
        assert_eq!(offset_of!(Callbacks, get_egl_display), 64);
        assert_eq!(size_of::<Callbacks>(), 72);
    }

    /// The renderer fills one of these and the VMM reads it, so a field in the wrong place is a
    /// context created to the wrong description -- or, for `shared`, one that shares with nothing
    /// and quietly renders into a namespace of its own.
    ///
    /// Ground truth: `offsetof` under `cc` on `src/virglrenderer.h`.
    #[test]
    fn the_gl_context_param_matches_the_c_header() {
        use std::mem::{offset_of, size_of};
        assert_eq!(offset_of!(GlCtxParam, version), 0);
        assert_eq!(offset_of!(GlCtxParam, shared), 4);
        assert_eq!(offset_of!(GlCtxParam, major_ver), 8);
        assert_eq!(offset_of!(GlCtxParam, minor_ver), 12);
        assert_eq!(offset_of!(GlCtxParam, compat_ctx), 16);
        assert_eq!(size_of::<GlCtxParam>(), 20);
    }

    /// `virgl_renderer_execute` reads its request through these structs and writes its answer
    /// back into the caller's own storage, so every offset here is a place the shim writes into
    /// memory it does not own. A field that drifted would corrupt silently.
    ///
    /// Ground truth: `harness/abi/layout.txt`, dumped by the compiler from the header.
    #[test]
    fn the_execute_structs_match_the_c_header() {
        use std::mem::{offset_of, size_of};

        assert_eq!(offset_of!(ExecuteHdr, stype), 0);
        assert_eq!(offset_of!(ExecuteHdr, stype_version), 4);
        assert_eq!(offset_of!(ExecuteHdr, size), 8);
        assert_eq!(size_of::<ExecuteHdr>(), 12);

        assert_eq!(offset_of!(ExportQuery, hdr), 0);
        assert_eq!(offset_of!(ExportQuery, in_resource_id), 12);
        assert_eq!(offset_of!(ExportQuery, out_num_fds), 16);
        assert_eq!(offset_of!(ExportQuery, in_export_fds), 20);
        assert_eq!(offset_of!(ExportQuery, out_fourcc), 24);
        assert_eq!(offset_of!(ExportQuery, out_fds), 32);
        assert_eq!(offset_of!(ExportQuery, out_strides), 48);
        assert_eq!(offset_of!(ExportQuery, out_offsets), 64);
        assert_eq!(offset_of!(ExportQuery, out_modifier), 80);
        assert_eq!(size_of::<ExportQuery>(), 88);

        assert_eq!(offset_of!(SupportedStructures, hdr), 0);
        assert_eq!(offset_of!(SupportedStructures, in_stype_version), 12);
        assert_eq!(offset_of!(SupportedStructures, out_supported_structures_mask), 16);
        assert_eq!(size_of::<SupportedStructures>(), 20);
    }

    /// The version gate in `virgl_renderer_init` is what makes those projections legal: a caller
    /// declaring v3 allocates through `get_server_fd` and no further. Both fields the shim reads
    /// must therefore end inside that prefix -- and `get_egl_display`, being v4, must not, or a
    /// `&Callbacks` would be claiming bytes even a conforming caller never allocated.
    #[test]
    fn the_fields_init_reads_end_inside_the_v3_prefix() {
        use std::mem::{offset_of, size_of};
        let ptr = size_of::<*mut c_void>();
        let v3_prefix = offset_of!(Callbacks, get_server_fd) + ptr;
        assert!(offset_of!(Callbacks, write_fence) + ptr <= v3_prefix);
        assert!(offset_of!(Callbacks, write_context_fence) + ptr <= v3_prefix);
        assert!(offset_of!(Callbacks, get_egl_display) >= v3_prefix);
    }
}
